POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0MzdjNjA0NDVlYzM4M2ZiMDVlYzAzYSIsImlhdCI6MTY5NjQyMTkzMiwiZXhwIjoxNjk2NDI1NTMyfQ.v9Tsgz0J8I911BR9so7TJaJ09Wc_M3m-nTfSesz7Ttw

{
  "title": "React Pattern",
  "author": "Michael Chann",
  "url": "https://reactpatterns.com/",
  "likes": 10
}